// <auto-generated />
using System;
using Database.Logic.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Database.Migrations
{
    [DbContext(typeof(BaseEfDatabaseContext))]
    partial class BaseEfDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Database.Model.Shared.Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("StreetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StreetNumber")
                        .HasColumnType("int");

                    b.HasKey("AddressId");

                    b.HasIndex("PostalCode");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Database.Model.Shared.BusinessItem", b =>
                {
                    b.Property<Guid>("BusinessItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MandatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BusinessItemId");

                    b.HasIndex("AddressId");

                    b.HasIndex("MandatorId");

                    b.ToTable("BusinessItems");
                });

            modelBuilder.Entity("Database.Model.Shared.City", b =>
                {
                    b.Property<int>("PostalCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostalCode");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Database.Model.Shared.Mandator", b =>
                {
                    b.Property<Guid>("MandatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MandatorId");

                    b.HasIndex("AddressId");

                    b.ToTable("Mandators");
                });

            modelBuilder.Entity("Database.Model.Shared.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BusinessItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.HasIndex("AddressId");

                    b.HasIndex("BusinessItemId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Database.Model.Shared.Address", b =>
                {
                    b.HasOne("Database.Model.Shared.City", "City")
                        .WithMany("AddressList")
                        .HasForeignKey("PostalCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Database.Model.Shared.BusinessItem", b =>
                {
                    b.HasOne("Database.Model.Shared.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("Database.Model.Shared.Mandator", "Mandator")
                        .WithMany("BusinessItemList")
                        .HasForeignKey("MandatorId");
                });

            modelBuilder.Entity("Database.Model.Shared.Mandator", b =>
                {
                    b.HasOne("Database.Model.Shared.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");
                });

            modelBuilder.Entity("Database.Model.Shared.Person", b =>
                {
                    b.HasOne("Database.Model.Shared.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("Database.Model.Shared.BusinessItem", "BusinessItem")
                        .WithMany("PersonList")
                        .HasForeignKey("BusinessItemId");
                });
#pragma warning restore 612, 618
        }
    }
}
